server:
  port: 8080

spring:
  application:
    name: mtracker
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${L_MT_MYSQL_URL}
    username: ${L_MT_MYSQL_USERNAME}
    password: ${L_MT_MYSQL_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${L_MT_MAIL_USERNAME}
    password: ${L_MT_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

springdoc:
  swagger-ui:
    path: /swagger
  api-docs:
    path: /api-docs

logging:
  level:
    org:
      springframework:
        security: TRACE

security:
  jwt:
    secret-key: ${L_MT_JWT_SECRET_KEY}
    expiration-time: ${L_MT_JWT_EXPIRATION_TIME}

aws:
  region: eu-central-1
  access-key-id: ${L_MT_AWS_ACCESS_KEY_ID}
  secret-access-key: ${L_MT_AWS_SECRET_KEY}
  s3:
    bucket-name: ${L_MT_AWS_S3_BUCKET_NAME}